name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BEFORE_BUILD_LINUX: "bash eng/install-dotnet.sh"
          CIBW_ENVIRONMENT_LINUX: DOTNET_ROOT="/tmp/dotnet" DOTNET_VERSION="6.0.100"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
